/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sprint } from "./Sprint";
import { SprintCountArgs } from "./SprintCountArgs";
import { SprintFindManyArgs } from "./SprintFindManyArgs";
import { SprintFindUniqueArgs } from "./SprintFindUniqueArgs";
import { DeleteSprintArgs } from "./DeleteSprintArgs";
import { SprintService } from "../sprint.service";
@graphql.Resolver(() => Sprint)
export class SprintResolverBase {
  constructor(protected readonly service: SprintService) {}

  async _sprintsMeta(
    @graphql.Args() args: SprintCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sprint])
  async sprints(@graphql.Args() args: SprintFindManyArgs): Promise<Sprint[]> {
    return this.service.sprints(args);
  }

  @graphql.Query(() => Sprint, { nullable: true })
  async sprint(
    @graphql.Args() args: SprintFindUniqueArgs
  ): Promise<Sprint | null> {
    const result = await this.service.sprint(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sprint)
  async deleteSprint(
    @graphql.Args() args: DeleteSprintArgs
  ): Promise<Sprint | null> {
    try {
      return await this.service.deleteSprint(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
